"""C3 curriculum alignment for G1-康軒-109上-期中1 (see qlp_items_g1_kangxuan_109a_midterm1.py).
Publisher chapters: 康軒 G1 上 (9 chapters). Skill names: skill-official-alignment.json G1-*.
"""

from __future__ import annotations

CH2 = ("康軒", "G1", "上", 2)
CH4 = ("康軒", "G1", "上", 4)
CH5 = ("康軒", "G1", "上", 5)
CH6 = ("康軒", "G1", "上", 6)
CH7 = ("康軒", "G1", "上", 7)
CH3 = ("康軒", "G1", "上", 3)

ALIGN = {
    "q01": dict(officialContentCodes=["N-1-2", "N-1-3"], publisherChapter=CH7,
                candidateSkillIds=["G1-06-03"], alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["official N-1-2/N-1-3 加法和減法", f"publisher {CH7}",
                                    "連連看配對雖含加法但屬遊戲化題型，非單一skill精確對應"]),
    "q02": dict(officialContentCodes=["N-1-2", "N-1-3"], publisherChapter=CH4,
                candidateSkillIds=["G1-04-02", "G1-04-03"], alignmentStatus="direct",
                alignmentConfidence="high",
                alignmentEvidence=["official N-1-2/3 加減", f"publisher {CH4}",
                                    "skill G1-04-02/03「2至5/6至10各數的分與合」對應10的配對湊十"]),
    "q03": dict(officialContentCodes=["S-1-1"], publisherChapter=CH2,
                candidateSkillIds=["G1-02-03"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["official S-1-1 長度(同N-1-5)", f"publisher {CH2}",
                                    "skill G1-02-03「認識點、直線和曲線」直接對應"]),
    "q04": dict(officialContentCodes=["S-1-1"], publisherChapter=CH2,
                candidateSkillIds=["G1-02-01"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["official S-1-1", f"publisher {CH2}",
                                    "skill G1-02-01「直接比較長度-長短、寬窄」對應繩子長短排序"]),
    "q05": dict(officialContentCodes=["S-1-1"], publisherChapter=CH2,
                candidateSkillIds=["G1-02-05"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["skill G1-02-05「用最高、最矮…描述物件」對應植物高矮排序"]),
    "q06a": dict(officialContentCodes=["S-1-1"], publisherChapter=CH2,
                 candidateSkillIds=["G1-02-04"], alignmentStatus="direct", alignmentConfidence="high",
                 alignmentEvidence=["skill G1-02-04「直接比較長度-高矮、厚薄」對應書本厚薄"]),
    "q06b": dict(officialContentCodes=["S-1-1"], publisherChapter=CH2,
                 candidateSkillIds=["G1-02-04"], alignmentStatus="direct", alignmentConfidence="high",
                 alignmentEvidence=["同 q06a：漢堡堆疊厚薄比較"]),
    "q07": dict(officialContentCodes=["N-1-2", "N-1-3"], publisherChapter=CH4,
                candidateSkillIds=["G1-04-03"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["10=5+5 數字分解，對應 G1-04-03「6至10各數的分與合」"]),
    "q08": dict(officialContentCodes=["N-1-2", "N-1-3"], publisherChapter=CH4,
                candidateSkillIds=["G1-04-03"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["7=3+4 數字分解，對應 G1-04-03"]),
    "q09": dict(officialContentCodes=["N-1-1"], publisherChapter=CH6,
                candidateSkillIds=["G1-08-05"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["official N-1-1 一百以內的數", f"publisher {CH6}",
                                    "28→23 倒數-1數列，對應 G1-08-05「運用倒數，求更小的數字」"]),
    "q10": dict(officialContentCodes=["N-1-1"], publisherChapter=CH6,
                candidateSkillIds=["G1-08-04"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["9→14 順數+1數列，對應 G1-08-04「運用順數，求更大的數字」"]),
    "q11": dict(officialContentCodes=["N-1-1"], publisherChapter=CH3,
                candidateSkillIds=["G1-03-02"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["蝴蝶排第幾個/後面幾個，對應 G1-03-02「次序和數量」"]),
    "q12": dict(officialContentCodes=["N-1-1"], publisherChapter=CH3,
                candidateSkillIds=["G1-03-02"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["狗排第幾個/前面幾個，對應 G1-03-02"]),
    "q13": dict(officialContentCodes=["N-1-1"], publisherChapter=CH3,
                candidateSkillIds=["G1-03-03"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["青蛙前後鄰位，對應 G1-03-03「前、後和之間」"]),
    "q14": dict(officialContentCodes=["S-1-2"], publisherChapter=CH5,
                candidateSkillIds=["G1-05-05"], alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["official S-1-2 形體的操作", f"publisher {CH5}",
                                    "skill G1-05-05「從複合圖形中辨別平面圖形」語意相近，"
                                    "惟本題正方形/長方形/三角形/圓形計數涵蓋平面圖形範疇，"
                                    "康軒G1上並無獨立平面圖形辨識章節，列partial"]),
    "q15": dict(officialContentCodes=["S-1-2"], publisherChapter=CH5,
                candidateSkillIds=["G1-05-05"], alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["同 q14：長方形計數"]),
    "q16": dict(officialContentCodes=["S-1-2"], publisherChapter=CH5,
                candidateSkillIds=["G1-05-05"], alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["同 q14：三角形計數"]),
    "q17": dict(officialContentCodes=["S-1-2"], publisherChapter=CH5,
                candidateSkillIds=["G1-05-05"], alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["同 q14：圓形計數"]),
    "q18": dict(officialContentCodes=["N-1-2", "N-1-3"], publisherChapter=CH7,
                candidateSkillIds=["G1-06-03"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["4+2=6，對應 G1-06-03「10以內的加法」"]),
    "q19": dict(officialContentCodes=["N-1-2", "N-1-3"], publisherChapter=CH7,
                candidateSkillIds=["G1-06-03"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["0+6=6，對應 G1-06-03"]),
    "q20": dict(officialContentCodes=["N-1-2", "N-1-3"], publisherChapter=CH7,
                candidateSkillIds=["G1-06-03"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["9+0=9，對應 G1-06-03"]),
    "q21": dict(officialContentCodes=["N-1-2", "N-1-3"], publisherChapter=CH7,
                candidateSkillIds=["G1-06-03"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["1+8=9，對應 G1-06-03"]),
    "q22": dict(officialContentCodes=["N-1-2", "N-1-3"], publisherChapter=CH7,
                candidateSkillIds=["G1-06-03"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["3+5=8，對應 G1-06-03"]),
    "q23": dict(officialContentCodes=["N-1-2", "N-1-3"], publisherChapter=CH7,
                candidateSkillIds=["G1-06-03"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["7+3=10，對應 G1-06-03"]),
    "q24": dict(officialContentCodes=["S-1-2"], publisherChapter=CH5,
                candidateSkillIds=["G1-05-01"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["official S-1-2", f"publisher {CH5}",
                                    "skill G1-05-01「認識立體圖形」對應平面/彎曲面物品分類"]),
    "q25": dict(officialContentCodes=["S-1-2"], publisherChapter=CH5,
                candidateSkillIds=["G1-05-01"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["同 q24：只有彎面物品"]),
    "q26": dict(officialContentCodes=["S-1-2"], publisherChapter=CH5,
                candidateSkillIds=["G1-05-01"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["容易堆疊滾動判斷，對應 G1-05-01 立體圖形性質認識"]),
    "q27": dict(officialContentCodes=["S-1-2"], publisherChapter=CH5,
                candidateSkillIds=["G1-05-01"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["同 q26：不容易堆疊"]),
    "q28": dict(officialContentCodes=["N-1-1"], publisherChapter=CH6,
                candidateSkillIds=["G1-08-01"], alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["official N-1-1", f"publisher {CH6}",
                                    "氣球計數16個涉及20以內數數，對應G1-08-01但本題為圖像計數"
                                    "非標準數數練習，列partial"]),
    "q29": dict(officialContentCodes=["N-1-1"], publisherChapter=CH6,
                candidateSkillIds=["G1-08-01"], alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["同 q28：棒球計數23個"]),
    "q30": dict(officialContentCodes=["N-1-2", "N-1-3"], publisherChapter=CH7,
                candidateSkillIds=["G1-06-04"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["5+4=9 應用題，對應 G1-06-04「10以內的加法應用題」"]),
    "q31": dict(officialContentCodes=["N-1-2", "N-1-3"], publisherChapter=CH7,
                candidateSkillIds=["G1-06-04"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["7+3=10 應用題，對應 G1-06-04"]),
    "q32": dict(officialContentCodes=["N-1-2", "N-1-3"], publisherChapter=CH7,
                candidateSkillIds=["G1-06-04"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["2+3=5 應用題，對應 G1-06-04"]),
}
