"""C3 curriculum alignment for G3-翰林-108上-期中1 (see qlp_items_g3_hanlin_108a_midterm1.py).
Publisher chapters from publisher-unit-alignment.json (翰林, G3, 上, 9 chapters).
Skill names from skill-official-alignment.json (chapterId G3-01.. etc).
"""

from __future__ import annotations

CH1 = ("翰林", "G3", "上", 1)
CH3 = ("翰林", "G3", "上", 3)
CH5 = ("翰林", "G3", "上", 5)
CH9 = ("翰林", "G3", "上", 9)

ALIGN = {
    "q01": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["official N-3-1 一萬以內的數", f"publisher {CH1}",
                                    "skill G3-01-02 認識千位的概念，對應2千4百5十位值合成"]),
    "q02": dict(officialContentCodes=["N-3-11"], publisherChapter=CH5, candidateSkillIds=["G3-09-01"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["official N-3-11 整數數線", f"publisher {CH5}",
                                    "skill G3-09-01 以毫米為單位比較長度／數線單位1，對應數線減1"]),
    "q03": dict(officialContentCodes=["N-3-11"], publisherChapter=CH5, candidateSkillIds=[],
                alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["數線區間格數計算(67→73)，屬N-3-11數線範疇但無單一對應skill"]),
    "q04": dict(officialContentCodes=["N-3-11"], publisherChapter=CH5, candidateSkillIds=[],
                alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["數線減法(54-6=48)，同q03"]),
    "q05": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["四位數千位數字最小值判斷，對應 G3-01-02 認識千位的概念"]),
    "q06": dict(officialContentCodes=["N-3-11"], publisherChapter=CH5, candidateSkillIds=[],
                alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["數線跳格(-10x4)，屬N-3-11但無單一對應skill"]),
    "q07": dict(officialContentCodes=["N-3-11"], publisherChapter=CH5, candidateSkillIds=[],
                alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["數線移動(+4-5)，同q06"]),
    "q08": dict(officialContentCodes=["N-3-2"], publisherChapter=CH3, candidateSkillIds=["G3-05-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["official N-3-2 加減直式計算", f"publisher {CH3}",
                                    "skill G3-05-02 三個數的加法，對應1279+215+1279應用題"]),
    "q09": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-04"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["三數排序(1005/992/929)，對應 G3-01-04 比較大小-千位數字相同"]),
    "q10": dict(officialContentCodes=["N-3-11"], publisherChapter=CH5, candidateSkillIds=[],
                alignmentStatus="uncertain", alignmentConfidence="low",
                alignmentEvidence=["數線等距刻度推算，需圖像判讀且本卷已裁圖覆核，"
                                    "惟無對應正式skill條目，保留uncertain"]),
    "q11": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["位值合成(2千1十8一=2018)，對應 G3-01-02"]),
    "q12": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["位值分解(1372拆千百十個)，對應 G3-01-02"]),
    "q13": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["2153=2000+100+□+3 位值拆解，對應 G3-01-02"]),
    "q14": dict(officialContentCodes=["N-3-11"], publisherChapter=CH5, candidateSkillIds=[],
                alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["數線等差+5填空，屬N-3-11但無單一對應skill"]),
    "q15": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["位值合成+讀法(3019=三千零十九)，對應 G3-01-02"]),
    "q16": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-06"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["等差+100數列(6800-7400)，對應 G3-01-06 順數和倒數"]),
    "q17": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["3886位值分解，對應 G3-01-02"]),
    "q18": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-06"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["等差+10數列(960-1030)，對應 G3-01-06"]),
    "q19": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-02"],
                alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["鈔票/硬幣清點求總金額，位值概念相關但非教材正式skill定義範圍"]),
    "q20": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-06"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["等差+100雙向數列(8800-9300)，對應 G3-01-06"]),
    "q21": dict(officialContentCodes=["N-3-2"], publisherChapter=CH3, candidateSkillIds=[],
                alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["生日日期加法(20+5=25)，屬簡單加法但非本冊正式時間章節"]),
    "q22": dict(officialContentCodes=["N-3-6"], publisherChapter=None, candidateSkillIds=[],
                alignmentStatus="uncertain", alignmentConfidence="low",
                alignmentEvidence=["official N-3-6 解題(排隊間隔應用)，翰林G3上出版社章節無"
                                    "對應此類排隊間隔題型之明確條目，保留uncertain"]),
    "q23": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["4507填入位值表，對應 G3-01-02"]),
    "q24": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-07"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["「八千零三」讀法轉數字，對應 G3-01-07/G3-01-02 位值概念"]),
    "q25": dict(officialContentCodes=["N-3-2"], publisherChapter=CH3, candidateSkillIds=[],
                alignmentStatus="uncertain", alignmentConfidence="low",
                alignmentEvidence=["835-568差幾人：answerStatus已標needs_review(答案卷與獨立"
                                    "驗算不符)，對齊亦保留uncertain，不因對齊掩蓋答案爭議"]),
    "q26": dict(officialContentCodes=["N-3-2"], publisherChapter=CH3, candidateSkillIds=["G3-05-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["3674+5931=9605 直式加法填空，對應 G3-05-02"]),
    "q27": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-05"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["夾擠範圍(2899<x<2905)求百位數字，對應 G3-01-05 比較大小-"
                                    "千位和百位數字相同"]),
    "q28": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-03"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["4469 vs 4489 比大小，對應 G3-01-03/04 比較大小"]),
    "q29": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["一千零二 vs 一千零二十，對應位值讀法與比較"]),
    "q30": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-03"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["7208 vs 6995，對應 G3-01-03 比較大小-千位數字不同"]),
    "q31": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-04"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["5006 vs 5060，對應 G3-01-04"]),
    "q32": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-04"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["3509 vs 3590，對應 G3-01-04"]),
    "q33": dict(officialContentCodes=["N-3-2"], publisherChapter=CH3, candidateSkillIds=["G3-05-03"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["581-267 直式減法，對應 G3-05-03 三個數的減法(簡化為二數)"]),
    "q34": dict(officialContentCodes=["N-3-2"], publisherChapter=CH3, candidateSkillIds=["G3-05-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["1523+5588 直式加法，對應 G3-05-02"]),
    "q35": dict(officialContentCodes=["N-3-2"], publisherChapter=CH3, candidateSkillIds=["G3-05-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["540+2560 直式加法，對應 G3-05-02"]),
    "q36": dict(officialContentCodes=["N-3-2"], publisherChapter=CH3, candidateSkillIds=["G3-05-03"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["1983-785 直式減法，對應 G3-05-03"]),
    "q37": dict(officialContentCodes=["N-3-2"], publisherChapter=CH3, candidateSkillIds=["G3-05-03"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["800-375 減法應用題，對應 G3-05-03"]),
    "q38": dict(officialContentCodes=["N-3-2"], publisherChapter=CH3, candidateSkillIds=["G3-05-03"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["5900-4629 差額比較應用題，對應 G3-05-03"]),
    "q39": dict(officialContentCodes=["N-3-2"], publisherChapter=CH3, candidateSkillIds=["G3-05-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["1805+2718 加法應用題，對應 G3-05-02"]),
    "q40": dict(officialContentCodes=["N-3-11"], publisherChapter=CH5, candidateSkillIds=[],
                alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["數線減法應用(18-9)，屬N-3-11但無單一對應skill"]),
    "q41": dict(officialContentCodes=["N-3-6"], publisherChapter=None, candidateSkillIds=[],
                alignmentStatus="uncertain", alignmentConfidence="low",
                alignmentEvidence=["跳格次數應用題(31-18=13次)，翰林G3上出版社章節無明確"
                                    "對應條目，保留uncertain"]),
    "q42": dict(officialContentCodes=["N-3-2"], publisherChapter=CH3, candidateSkillIds=["G3-05-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["634+895 兩步驟差額相加應用題，對應 G3-05-02"]),
}
