"""C3 curriculum alignment for G2-翰林-113上-期末2 (see qlp_items_g2_hanlin_113a_final2.py).
Publisher chapters: 翰林 G2 上 (10 chapters).
"""

from __future__ import annotations

CH4 = ("翰林", "G2", "上", 4)
CH6 = ("翰林", "G2", "上", 6)
CH7 = ("翰林", "G2", "上", 7)
CH8 = ("翰林", "G2", "上", 8)
CH10 = ("翰林", "G2", "上", 10)

ALIGN = {
    "q01": dict(officialContentCodes=["N-2-3", "N-2-4"], publisherChapter=CH4,
                candidateSkillIds=["G2-03-02"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["official N-2-3/4 解題", f"publisher {CH4}",
                                    "52-18-16 連續減法應用題，對應 G2-03-02 減法應用題(一)"]),
    "q02": dict(officialContentCodes=["N-2-6", "N-2-7"], publisherChapter=CH7,
                candidateSkillIds=["G2-06-02"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["official N-2-6/7 乘法/十十乘法", f"publisher {CH7}",
                                    "skill G2-06-02「用加法算乘法」對應連加式與乘法式辨異"]),
    "q03": dict(officialContentCodes=["N-2-13"], publisherChapter=CH8,
                candidateSkillIds=["G2-07-03"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["official N-2-13 鐘面的時刻", f"publisher {CH8}",
                                    "skill G2-07-03「以時和分報時(二)」對應7時55分判讀"]),
    "q04": dict(officialContentCodes=["N-2-6"], publisherChapter=CH7,
                candidateSkillIds=["G2-06-01"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["skill G2-06-01「乘法概念(一)-幾個幾」對應被乘數/乘數/積概念"]),
    "q05": dict(officialContentCodes=["N-2-3", "N-2-4"], publisherChapter=CH4,
                candidateSkillIds=["G2-03-04"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["skill G2-03-04「加減應用題-驗算」對應紅色緞帶兩種解法互驗"]),
    "q06": dict(officialContentCodes=["N-2-6", "N-2-7"], publisherChapter=CH7,
                candidateSkillIds=["G2-06-01"], alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["8x9與8x6相差幾個8，涉及乘法分配概念，該章skill未逐項"
                                    "涵蓋此比較型題，列partial"]),
    "q07": dict(officialContentCodes=["N-2-6", "N-2-7"], publisherChapter=CH7,
                candidateSkillIds=["G2-06-01"], alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["同 q06：7x3與7x7相差"]),
    "q08": dict(officialContentCodes=["N-2-6", "N-2-7"], publisherChapter=CH7,
                candidateSkillIds=["G2-06-01", "G2-06-02"], alignmentStatus="direct",
                alignmentConfidence="high",
                alignmentEvidence=["4串葡萄x9顆，連加式與乘法式互換，對應 G2-06-01/02"]),
    "q09": dict(officialContentCodes=["N-2-6"], publisherChapter=CH7, candidateSkillIds=["G2-06-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["5隻瓢蟲x6腳連加式，對應 G2-06-02"]),
    "q10": dict(officialContentCodes=["N-2-6"], publisherChapter=CH7, candidateSkillIds=["G2-06-01"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["同題乘法式6x5=30，對應 G2-06-01"]),
    "q11": dict(officialContentCodes=["N-2-6"], publisherChapter=CH7, candidateSkillIds=["G2-06-01"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["4x5=20被乘數/乘數/積名稱，對應 G2-06-01 乘法概念"]),
    "q12": dict(officialContentCodes=["N-2-13"], publisherChapter=CH8, candidateSkillIds=["G2-07-04"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["skill G2-07-04「以小時為單位求時間間隔」延伸至分鐘級"
                                    "(3:00走20分到3:20)，語意相符"]),
    "q13": dict(officialContentCodes=["N-2-12", "S-2-5"], publisherChapter=CH10,
                candidateSkillIds=["G2-09-01"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["official N-2-12/S-2-5 容量重量面積", f"publisher {CH10}",
                                    "skill G2-09-01「直接比較面積」對應甲乙丙面積大小排序"]),
    "q14": dict(officialContentCodes=["N-2-6"], publisherChapter=CH7, candidateSkillIds=["G2-06-01"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["連連看算式配對答案，對應乘法/連加概念 G2-06-01"]),
    "q15": dict(officialContentCodes=["N-2-13"], publisherChapter=CH8, candidateSkillIds=["G2-07-03"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["鐘面報讀11:25，對應 G2-07-03"]),
    "q16": dict(officialContentCodes=["N-2-13"], publisherChapter=CH8, candidateSkillIds=["G2-07-03"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["鐘面報讀6:30，對應 G2-07-03"]),
    "q17": dict(officialContentCodes=["N-2-13"], publisherChapter=CH8, candidateSkillIds=["G2-07-03"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["選擇符合7點多的鐘面，對應 G2-07-03"]),
    "q18": dict(officialContentCodes=["N-2-13"], publisherChapter=CH8, candidateSkillIds=["G2-07-03"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["選擇符合5點多的鐘面，對應 G2-07-03"]),
    "q19": dict(officialContentCodes=["N-2-6"], publisherChapter=CH7, candidateSkillIds=["G2-06-01"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["5人x9隊=45人 乘法應用題，對應 G2-06-01"]),
    "q20": dict(officialContentCodes=["N-2-3", "N-2-4"], publisherChapter=CH4,
                candidateSkillIds=["G2-03-02"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["75+15-68=22 加減應用題，對應 G2-03-02"]),
    "q21": dict(officialContentCodes=["N-2-13"], publisherChapter=CH8, candidateSkillIds=["G2-07-04"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["7時到11時經過4小時，對應 G2-07-04「以小時為單位求時間間隔」"]),
    "q22": dict(officialContentCodes=["N-2-13"], publisherChapter=CH8, candidateSkillIds=["G2-07-04"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["8:00至8:45分針走幾大格，對應 G2-07-04"]),
    "q23": dict(officialContentCodes=["N-2-12", "S-2-5"], publisherChapter=CH10,
                candidateSkillIds=["G2-09-01"], alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["不規則方格圖面積計數(甲12/乙13/丙15)，對應面積比較"
                                    "chapter但涉及方格計數技巧非該章單一skill完整涵蓋"]),
    "q24": dict(officialContentCodes=["N-2-5"], publisherChapter=CH6, candidateSkillIds=["G2-05-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["official N-2-5 解題(兩步驟)", f"publisher {CH6}",
                                    "18-5=13;18+13=31 對應 G2-05-02「減法應用題(二)-兩步驟」"]),
    "q25": dict(officialContentCodes=["N-2-5"], publisherChapter=CH6, candidateSkillIds=["G2-05-01"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["25+32=57;57+19=76 對應 G2-05-01「加法應用題(二)-兩步驟」"]),
    "q26": dict(officialContentCodes=["N-2-5"], publisherChapter=CH6, candidateSkillIds=["G2-05-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["95-48-15=32 對應 G2-05-02"]),
}
