"""C3 curriculum alignment for G3-康軒-113上-期中1 (see qlp_items_g3_kangxuan_113a_midterm1.py).
Publisher chapters: 康軒 G3 上 (9 chapters).
"""

from __future__ import annotations

CH1 = ("康軒", "G3", "上", 1)
CH2 = ("康軒", "G3", "上", 2)
CH3 = ("康軒", "G3", "上", 3)
CH4 = ("康軒", "G3", "上", 4)

ALIGN = {
    "q01": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-06"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["8588→8628 等差+10數列，對應 G3-01-06 順數和倒數"]),
    "q02": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-06"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["5326→4926 等差-100數列，對應 G3-01-06"]),
    "q03": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["8個千22個十17個一合成8237，對應 G3-01-02 認識千位的概念"]),
    "q04": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["數字卡組成最大/最小四位數，對應 G3-01-02"]),
    "q05": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-05"],
                alignmentStatus="uncertain", alignmentConfidence="low",
                alignmentEvidence=["official N-3-1", f"publisher {CH1}",
                                    "skill G3-01-05 比較大小-千位百位相同 主題相符，"
                                    "惟本題 answerStatus 已因答案卷數值與獨立驗算不符而"
                                    "標記 needs_review，對齊亦保留uncertain避免掩蓋爭議"]),
    "q06": dict(officialContentCodes=["N-3-2"], publisherChapter=CH2, candidateSkillIds=["G3-05-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["1895+490=2385 三位數加法應用題，對應 G3-05-02"]),
    "q07": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["百位十位未知求最大/最小手錶標價，對應 G3-01-02"]),
    "q08": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=["G3-01-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["同 q07：最少可能付多少元"]),
    "q09": dict(officialContentCodes=["N-3-11"], publisherChapter=None, candidateSkillIds=[],
                alignmentStatus="uncertain", alignmentConfidence="low",
                alignmentEvidence=["official N-3-11 整數數線；毛毛蟲數線移動題，康軒G3上"
                                    "章節表無獨立數線章節(該內容於翰林版列為第5章)，"
                                    "版本間單元不可互用，保留uncertain"]),
    "q10": dict(officialContentCodes=["N-3-11"], publisherChapter=None, candidateSkillIds=[],
                alignmentStatus="uncertain", alignmentConfidence="low",
                alignmentEvidence=["同 q09：數線移動方向判斷"]),
    "q11": dict(officialContentCodes=["N-3-12"], publisherChapter=CH3, candidateSkillIds=["G3-09-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["official N-3-12 長度", f"publisher {CH3}",
                                    "skill G3-09-02「毫米和公分間的互相轉換」對應62毫米=6公分2毫米"]),
    "q12": dict(officialContentCodes=["N-3-12"], publisherChapter=CH3, candidateSkillIds=["G3-09-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["同 q11：74毫米轉換"]),
    "q13": dict(officialContentCodes=["N-3-12"], publisherChapter=CH3, candidateSkillIds=["G3-09-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["同 q11：301毫米轉換"]),
    "q14": dict(officialContentCodes=["N-3-12"], publisherChapter=CH3, candidateSkillIds=["G3-09-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["最高最低雨量相差297毫米轉換，對應 G3-09-02"]),
    "q15": dict(officialContentCodes=["N-3-2"], publisherChapter=CH2, candidateSkillIds=["G3-05-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["2948+4257=7205 直式加法填空，對應 G3-05-02"]),
    "q16": dict(officialContentCodes=["N-3-2"], publisherChapter=CH2, candidateSkillIds=["G3-05-03"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["6504-1775=4729 直式減法填空，對應 G3-05-03"]),
    "q17": dict(officialContentCodes=["N-3-3"], publisherChapter=CH4, candidateSkillIds=["G3-02-03"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["723x5=3615 三位數乘一位數，對應 G3-02-03"]),
    "q18": dict(officialContentCodes=["N-3-3"], publisherChapter=CH4, candidateSkillIds=["G3-02-03"],
                alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["排列6,9,1求最大乘積，屬乘法應用之延伸思考題，非"
                                    "單一skill直接對應(該能力較接近數感/策略性佈局)"]),
    "q19": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=[],
                alignmentStatus="uncertain", alignmentConfidence="low",
                alignmentEvidence=["價格加總估算(595+399≈1000)，屬估算能力，官方108課綱"
                                    "與康軒教材皆未見獨立估算章節，保留uncertain"]),
    "q20": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=[],
                alignmentStatus="uncertain", alignmentConfidence="low",
                alignmentEvidence=["同 q19：差額估算"]),
    "q21": dict(officialContentCodes=["N-3-3"], publisherChapter=CH4, candidateSkillIds=[],
                alignmentStatus="uncertain", alignmentConfidence="low",
                alignmentEvidence=["4隻手套估算總價，同 q19 屬估算範疇"]),
    "q22": dict(officialContentCodes=["N-3-1"], publisherChapter=CH1, candidateSkillIds=[],
                alignmentStatus="uncertain", alignmentConfidence="low",
                alignmentEvidence=["900元購物估算最接近選項，同 q19"]),
    "q23": dict(officialContentCodes=["N-3-12"], publisherChapter=CH3, candidateSkillIds=["G3-09-01"],
                alignmentStatus="uncertain", alignmentConfidence="low",
                alignmentEvidence=["official N-3-12", f"publisher {CH3}",
                                    "紙條毫米量測題，因需實體量尺無法獨立驗算，"
                                    "answerStatus已標visual_manual_required，對齊信心亦降為uncertain"]),
    "q24": dict(officialContentCodes=["N-3-12"], publisherChapter=CH3, candidateSkillIds=["G3-09-01"],
                alignmentStatus="uncertain", alignmentConfidence="low",
                alignmentEvidence=["同 q23：紙條公分毫米量測"]),
    "q25": dict(officialContentCodes=["N-3-2"], publisherChapter=CH2, candidateSkillIds=["G3-05-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["4084+2935=7019 直式加法，對應 G3-05-02"]),
    "q26": dict(officialContentCodes=["N-3-2"], publisherChapter=CH2, candidateSkillIds=["G3-05-03"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["7030-2469=4561 直式減法，對應 G3-05-03"]),
    "q27": dict(officialContentCodes=["N-3-3"], publisherChapter=CH4, candidateSkillIds=["G3-02-01"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["649x5=3245 兩位數乘一位數，對應 G3-02-01"]),
    "q28": dict(officialContentCodes=["N-3-3"], publisherChapter=CH4, candidateSkillIds=["G3-02-03"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["408x7=2856 三位數乘一位數，對應 G3-02-03"]),
    "q29": dict(officialContentCodes=["N-3-12"], publisherChapter=CH3, candidateSkillIds=["G3-09-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["16公分9毫米-123毫米 長度單位混合減法，對應 G3-09-02"]),
    "q30": dict(officialContentCodes=["N-3-12"], publisherChapter=CH3, candidateSkillIds=["G3-09-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["76毫米+5公分3毫米 單位混合加法，對應 G3-09-02"]),
    "q31": dict(officialContentCodes=["N-3-12"], publisherChapter=CH3, candidateSkillIds=["G3-09-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["小蝸牛爬行距離公分毫米加法，對應 G3-09-02"]),
    "q32": dict(officialContentCodes=["N-3-12"], publisherChapter=CH3, candidateSkillIds=["G3-09-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["竹竿綁接總長度(含重疊扣除)，對應 G3-09-02"]),
    "q33": dict(officialContentCodes=["N-3-2"], publisherChapter=CH2, candidateSkillIds=["G3-05-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["1545+746=2291 加法應用題，對應 G3-05-02"]),
    "q34": dict(officialContentCodes=["N-3-2"], publisherChapter=CH2, candidateSkillIds=["G3-05-03"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["2291-355=1936 減法應用題，對應 G3-05-03"]),
    "q35": dict(officialContentCodes=["N-3-3"], publisherChapter=CH4, candidateSkillIds=["G3-02-04"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["295x6=1770 乘法應用題，對應 G3-02-04 乘法應用題(一)"]),
    "q36": dict(officialContentCodes=["N-3-3"], publisherChapter=CH4, candidateSkillIds=["G3-02-04"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["15x2=30;30x6=180 兩步驟乘法應用題，對應 G3-02-04"]),
}
