"""C3 curriculum alignment for G1-康軒-108上-期中2 (see qlp_items_g1_kangxuan_108a_midterm2.py).
Publisher chapters: 康軒 G1 上 (9 chapters, same table as G1-康軒-109上-期中1).
localId<->questionNumber cross-checked against the item file with rg before writing.
"""

from __future__ import annotations

CH1 = ("康軒", "G1", "上", 1)
CH2 = ("康軒", "G1", "上", 2)
CH3 = ("康軒", "G1", "上", 3)
CH4 = ("康軒", "G1", "上", 4)
CH5 = ("康軒", "G1", "上", 5)
CH6 = ("康軒", "G1", "上", 6)

ALIGN = {
    "q01": dict(officialContentCodes=["N-1-1"], publisherChapter=CH6, candidateSkillIds=["G1-08-05"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["official N-1-1 一百以內的數", f"publisher {CH6}",
                                    "15→10 倒數-1菱形鏈，對應 G1-08-05 運用倒數求更小的數字"]),
    "q02": dict(officialContentCodes=["N-1-1"], publisherChapter=CH6, candidateSkillIds=["G1-08-04"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["25→30 順數+1烏龜鏈，對應 G1-08-04 運用順數求更大的數字"]),
    "q03": dict(officialContentCodes=["N-1-1"], publisherChapter=CH3, candidateSkillIds=["G1-03-02"],
                alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["official N-1-1", f"publisher {CH3}",
                                    "海洋生物圖像計數填表，貼近 G1-03-02 次序和數量但屬"
                                    "混合物品計數非單一skill精確對應"]),
    "q04": dict(officialContentCodes=["N-1-1"], publisherChapter=CH3, candidateSkillIds=["G1-03-06"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["刀叉數量調整符合標示數字，對應 G1-03-06「比較-多和少」"]),
    "q05": dict(officialContentCodes=["N-1-1"], publisherChapter=CH3, candidateSkillIds=["G1-03-06"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["3個蛋糕vs8瓶蜂蜜多少比較，對應 G1-03-06"]),
    "q06": dict(officialContentCodes=["N-1-1"], publisherChapter=CH3, candidateSkillIds=["G1-03-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["從標示起點數第4個氣球塗色，對應 G1-03-02 次序和數量"]),
    "q07": dict(officialContentCodes=["N-1-1"], publisherChapter=CH3, candidateSkillIds=["G1-03-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["前面8棵樹塗色，對應 G1-03-02"]),
    "q08": dict(officialContentCodes=["N-1-2", "N-1-3"], publisherChapter=CH4,
                candidateSkillIds=["G1-04-02"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["4和2合起來是6，對應 G1-04-02「2至5各數的分與合」延伸"]),
    "q09": dict(officialContentCodes=["N-1-2", "N-1-3"], publisherChapter=CH4,
                candidateSkillIds=["G1-04-03"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["()和5合起來是8，對應 G1-04-03「6至10各數的分與合」"]),
    "q10": dict(officialContentCodes=["N-1-2", "N-1-3"], publisherChapter=CH4,
                candidateSkillIds=["G1-04-03"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["7和1合起來是8，對應 G1-04-03"]),
    "q11": dict(officialContentCodes=["N-1-2", "N-1-3"], publisherChapter=CH4,
                candidateSkillIds=["G1-04-03"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["9是由()和4合起來，對應 G1-04-03"]),
    "q12": dict(officialContentCodes=["N-1-2", "N-1-3"], publisherChapter=CH4,
                candidateSkillIds=["G1-04-02"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["5是由3和()合起來，對應 G1-04-02"]),
    "q13": dict(officialContentCodes=["N-1-2", "N-1-3"], publisherChapter=CH4,
                candidateSkillIds=["G1-04-03"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["10是由6和()合起來，對應 G1-04-03"]),
    "q14": dict(officialContentCodes=["S-1-1"], publisherChapter=CH2, candidateSkillIds=["G1-02-01"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["波浪繩子長度比較，對應 G1-02-01 直接比較長度-長短"]),
    "q15": dict(officialContentCodes=["S-1-1"], publisherChapter=CH2, candidateSkillIds=["G1-02-01"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["螺旋圖長度比較，對應 G1-02-01"]),
    "q16": dict(officialContentCodes=["S-1-1"], publisherChapter=CH2, candidateSkillIds=["G1-02-04"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["書本厚薄比較，對應 G1-02-04 直接比較長度-高矮、厚薄"]),
    "q17": dict(officialContentCodes=["S-1-1"], publisherChapter=CH2, candidateSkillIds=["G1-02-05"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["三名兒童身高最高最矮判斷，對應 G1-02-05"]),
    "q18": dict(officialContentCodes=["N-1-1"], publisherChapter=CH6, candidateSkillIds=["G1-08-03"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["19/26/30最大最小判斷，對應 G1-08-03「比較20以內、不多"
                                    "於4個數字的大小」"]),
    "q19": dict(officialContentCodes=["N-1-1"], publisherChapter=CH3, candidateSkillIds=["G1-03-06"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["三疊橢圓堆疊數量最多最少判斷，對應 G1-03-06"]),
    "q20": dict(officialContentCodes=["N-1-1"], publisherChapter=CH1,
                candidateSkillIds=["G1-01-01"], alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["圈出標示數量8個，對應 G1-01-01「10以內的數-數數」"]),
    "q21": dict(officialContentCodes=["N-1-1"], publisherChapter=CH3, candidateSkillIds=["G1-03-06"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["7張紙9個小朋友夠不夠判斷，對應 G1-03-06 比較多和少"]),
    "q22": dict(officialContentCodes=["N-1-1"], publisherChapter=CH6, candidateSkillIds=["G1-08-01"],
                alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["蜻蜓計數29隻，對應 G1-08-01 但為圖像計數非標準數數"
                                    "練習，列partial"]),
    "q23": dict(officialContentCodes=["S-1-2"], publisherChapter=CH5, candidateSkillIds=["G1-05-01"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["容易滾動物品判斷，對應 G1-05-01 認識立體圖形"]),
    "q24": dict(officialContentCodes=["S-1-2"], publisherChapter=CH5, candidateSkillIds=["G1-05-01"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["只有平平的面物品判斷，對應 G1-05-01"]),
    "q25": dict(officialContentCodes=["S-1-1"], publisherChapter=CH2, candidateSkillIds=["G1-02-05"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["比身高正確方法判斷，對應 G1-02-05"]),
    "q26": dict(officialContentCodes=["N-1-1"], publisherChapter=CH6, candidateSkillIds=["G1-08-03"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["比16大的數(12/19/14/21)判斷，對應 G1-08-03"]),
    "q27": dict(officialContentCodes=["S-1-2"], publisherChapter=CH5, candidateSkillIds=["G1-05-05"],
                alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["魚形複合圖形正方形計數(0個)，對應 G1-05-05「從複合"
                                    "圖形中辨別平面圖形」，惟康軒G1上無獨立平面圖形辨識"
                                    "章節，列partial"]),
    "q28": dict(officialContentCodes=["S-1-2"], publisherChapter=CH5, candidateSkillIds=["G1-05-05"],
                alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["同 q27：圓形計數"]),
    "q29": dict(officialContentCodes=["S-1-2"], publisherChapter=CH5, candidateSkillIds=["G1-05-05"],
                alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["同 q27：三角形計數"]),
    "q30": dict(officialContentCodes=["S-1-2"], publisherChapter=CH5, candidateSkillIds=["G1-05-05"],
                alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["機器人+泰迪熊複合圖形正方形計數，同 q27"]),
    "q31": dict(officialContentCodes=["S-1-2"], publisherChapter=CH5, candidateSkillIds=["G1-05-05"],
                alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["同 q30：長方形計數"]),
    "q32": dict(officialContentCodes=["S-1-2"], publisherChapter=CH5, candidateSkillIds=["G1-05-05"],
                alignmentStatus="partial", alignmentConfidence="medium",
                alignmentEvidence=["同 q30：三角形計數"]),
    "q33": dict(officialContentCodes=["S-1-1"], publisherChapter=CH2, candidateSkillIds=["G1-02-03"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["鉤狀線分類為曲線，對應 G1-02-03 認識點、直線和曲線"]),
    "q34": dict(officialContentCodes=["S-1-1"], publisherChapter=CH2, candidateSkillIds=["G1-02-03"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["直立短線分類為直線，對應 G1-02-03"]),
    "q35": dict(officialContentCodes=["S-1-1"], publisherChapter=CH2, candidateSkillIds=["G1-02-03"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["螺旋捲線分類為曲線，對應 G1-02-03"]),
    "q36": dict(officialContentCodes=["N-1-1"], publisherChapter=CH3, candidateSkillIds=["G1-03-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["書櫃由上數第3層書本數，對應 G1-03-02 次序和數量"]),
    "q37": dict(officialContentCodes=["N-1-1"], publisherChapter=CH3, candidateSkillIds=["G1-03-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["書櫃由下數第幾層有5本書，對應 G1-03-02"]),
    "q38": dict(officialContentCodes=["N-1-1"], publisherChapter=CH3, candidateSkillIds=["G1-03-03"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["采宣前面已拿完氣球人數，對應 G1-03-03「前、後和之間」"]),
    "q39": dict(officialContentCodes=["N-1-1"], publisherChapter=CH3, candidateSkillIds=["G1-03-02"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["怡敏排第幾位，對應 G1-03-02 次序和數量"]),
    "q40": dict(officialContentCodes=["N-1-1"], publisherChapter=CH3, candidateSkillIds=["G1-03-03"],
                alignmentStatus="direct", alignmentConfidence="high",
                alignmentEvidence=["采宣後面有幾人，對應 G1-03-03"]),
}
